### ISSUE TITLE
aria.sh not there

### ISSUE THREAD

**Issue by a092devs** [aryanvikash/ariabut#2]
You forgot to add aria.sh?

**Comment by aryanvikash** [comment]
This one is for my personal use😞 ....    use out386 repo

**Comment by a092devs** [comment]
> This one is for my personal use😞 .... use out386 repo

I got it bro, I want to use indexing so I am using yours, but I am not sure where to add index link. Can you show me some light? i checked index.js but didint find where to add it.

**Comment by aryanvikash** [comment]
@a092devs  Just create a variable of " INDEX_DOMAIN " in .  constant.js

`INDEX_DOMAIN : 'https://exmaple.worker.com/' `

**Comment by a092devs** [comment]
done thanks
